name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v3
      - uses: davidB/rust-cargo-make@v1
      - name: Run CI flow
        run: cargo make ci
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
